import pool from '../db';

/**
 * Serialise "check for an existing grant invoice with this DocNumber, then
 * create one" across every caller that can race on the same DocNumber.
 *
 * DocNumber for a grant invoice is the Baseline grant_id from ssg_grants —
 * shared, global data, not scoped to one pipeline. Two DIFFERENT code paths
 * compute and create against it (createDirectApplicationGrantInvoice for DA,
 * createCompanyApplicationGrantInvoice for CA), and each is itself reachable
 * from multiple independent triggers (email ingest, the cron sweep, the
 * manual "Generate Invoice" button, the post-SSG-sync hook, bulk upload).
 * Without a lock, two overlapping calls for the same DocNumber both pass the
 * "does it exist" check before either creates, and QuickBooks does not
 * reliably reject the resulting duplicate DocNumber for this company (the
 * fault-6140 safety net `qboCreateInvoiceRetryingDuplicateDocNumber` reacts
 * to never fires) — this is how the GRN-2607-108010 / GRN-2608-016202
 * duplicate invoices happened (2026-09-08 cleanup).
 *
 * Same pattern as `createDirectApplicationInvoice`'s enrolment-keyed lock,
 * but keyed on the DocNumber itself so it also closes the cross-pipeline gap
 * between the DA and CA grant-invoice creators.
 */
const GRANT_INVOICE_LOCK_WAIT_MS = 90_000;

export async function withGrantInvoiceDocNumberLock<T>(
  docNumber: string,
  fn: () => Promise<T>
): Promise<T> {
  const lockKey = `grant-inv:${docNumber.trim().toUpperCase()}`;
  const client = await pool.connect();
  let held = false;
  try {
    const deadline = Date.now() + GRANT_INVOICE_LOCK_WAIT_MS;
    while (Date.now() < deadline) {
      const res = await client.query(`SELECT pg_try_advisory_lock(hashtext($1)) AS locked`, [lockKey]);
      if (res.rows[0]?.locked) { held = true; break; }
      await new Promise((r) => setTimeout(r, 1000));
    }
    if (!held) {
      throw new Error(
        `A grant invoice for ${docNumber} is already being generated by another process. Try again in a moment.`
      );
    }
    return await fn();
  } finally {
    if (held) {
      await client.query(`SELECT pg_advisory_unlock(hashtext($1))`, [lockKey]).catch(() => {});
    }
    client.release();
  }
}
