-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_profile
(
    user_id uuid NOT NULL,
    tel text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.app_user
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    profile_picture_url text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.assessment
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    course_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    category assessment_category NOT NULL,
    status assessment_status NOT NULL,
    access_code text COLLATE pg_catalog."default",
    file_url text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT assessment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assessment_grade
(
    enrollment_id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    status grade_status NOT NULL,
    CONSTRAINT assessment_grade_pkey PRIMARY KEY (enrollment_id, assessment_id)
);

CREATE TABLE IF NOT EXISTS public.calendar_event
(
    id bigserial NOT NULL,
    course_id uuid,
    title text COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    type calendar_event_type NOT NULL,
    speaker text COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default",
    CONSTRAINT calendar_event_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.certification
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    trainer_id uuid,
    name text COLLATE pg_catalog."default" NOT NULL,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    original_filename text COLLATE pg_catalog."default",
    developer_id uuid,
    CONSTRAINT trainer_certification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_conversation
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_conversation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_message
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL,
    role chat_role NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_message_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    course_code text COLLATE pg_catalog."default",
    tsc_title text COLLATE pg_catalog."default",
    tsc_code text COLLATE pg_catalog."default",
    tsc_knowledge text COLLATE pg_catalog."default",
    tsc_abilities text COLLATE pg_catalog."default",
    learning_outcomes text COLLATE pg_catalog."default",
    training_hours numeric,
    assessment_hours numeric,
    difficulty text COLLATE pg_catalog."default",
    mode_of_learning mode_of_learning,
    course_type course_type,
    enrollment_status text COLLATE pg_catalog."default",
    status assessment_status,
    course_fee numeric(12, 2),
    tax_percent numeric(5, 2),
    is_wsq_funded boolean DEFAULT false,
    is_skills_future_eligible boolean DEFAULT false,
    is_psea_eligible boolean DEFAULT false,
    is_mces_eligible boolean DEFAULT false,
    is_ibf_funded boolean DEFAULT false,
    is_utap_eligible boolean DEFAULT false,
    start_date date,
    end_date date,
    class_status class_status,
    learner_guide_url text COLLATE pg_catalog."default",
    slides_url text COLLATE pg_catalog."default",
    lesson_plan_url text COLLATE pg_catalog."default",
    assessment_plan_url text COLLATE pg_catalog."default",
    facilitator_guide_url text COLLATE pg_catalog."default",
    trainer_slides_url text COLLATE pg_catalog."default",
    is_gamified boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT course_pkey PRIMARY KEY (id),
    CONSTRAINT course_course_code_key UNIQUE (course_code)
);

CREATE TABLE IF NOT EXISTS public.course_run
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    course_id uuid NOT NULL,
    course_run_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    digital_attendance_id text COLLATE pg_catalog."default",
    class_status class_status DEFAULT 'Pending'::class_status,
    start_date date,
    end_date date,
    mode_of_learning mode_of_learning,
    assigned_trainer_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT course_run_pkey PRIMARY KEY (id),
    CONSTRAINT uq_course_run_per_course UNIQUE (course_id, course_run_id)
);

CREATE TABLE IF NOT EXISTS public.course_run_assessment
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    course_run_id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    published boolean NOT NULL DEFAULT false,
    published_at timestamp with time zone,
    CONSTRAINT course_run_assessment_pkey PRIMARY KEY (id),
    CONSTRAINT course_run_assessment_course_run_id_assessment_id_key UNIQUE (course_run_id, assessment_id)
);

CREATE TABLE IF NOT EXISTS public.developer_profile
(
    user_id uuid NOT NULL,
    tel text COLLATE pg_catalog."default" NOT NULL,
    developer_type developer_type NOT NULL,
    cv_url text COLLATE pg_catalog."default",
    linkedin_url text COLLATE pg_catalog."default",
    gender gender,
    qualifications jsonb DEFAULT '{}'::jsonb,
    education text COLLATE pg_catalog."default" DEFAULT '{}'::jsonb,
    areas_of_specialty jsonb DEFAULT '{}'::jsonb,
    cv_original_filename text COLLATE pg_catalog."default",
    CONSTRAINT developer_profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    course_id uuid NOT NULL,
    course_run_id uuid NOT NULL,
    progress_percent numeric(5, 2) DEFAULT 0,
    payment_status learner_payment_status,
    assessment_status text COLLATE pg_catalog."default" DEFAULT 'Pending'::grade_status,
    course_sponsorship course_sponsorship,
    enrolment_date date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    certificate text COLLATE pg_catalog."default",
    CONSTRAINT enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT enrollment_user_id_course_run_id_key UNIQUE (user_id, course_run_id)
);

CREATE TABLE IF NOT EXISTS public.job_posting
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text COLLATE pg_catalog."default" NOT NULL,
    company text COLLATE pg_catalog."default" NOT NULL,
    location text COLLATE pg_catalog."default" NOT NULL,
    salary_min numeric(12, 2) NOT NULL,
    salary_max numeric(12, 2) NOT NULL,
    area text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    url text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT job_posting_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.learner_profile
(
    user_id uuid NOT NULL,
    tel text COLLATE pg_catalog."default" NOT NULL,
    nric text COLLATE pg_catalog."default",
    gender gender NOT NULL,
    company text COLLATE pg_catalog."default" NOT NULL,
    employment_status employment_status NOT NULL,
    nationality nationality NOT NULL,
    ethnicity ethnicity NOT NULL,
    dob date NOT NULL,
    invoice_url text COLLATE pg_catalog."default",
    receipt_url text COLLATE pg_catalog."default",
    pro_forma_url text COLLATE pg_catalog."default",
    CONSTRAINT learner_profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.learning_unit
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    course_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    "position" integer NOT NULL DEFAULT 1,
    CONSTRAINT learning_unit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provider_admin_user
(
    provider_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT provider_admin_user_pkey PRIMARY KEY (provider_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.ssg_claims
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    claim_id character varying(100) COLLATE pg_catalog."default",
    grant_id character varying(100) COLLATE pg_catalog."default",
    enrollment_id character varying(100) COLLATE pg_catalog."default",
    trainee_name character varying(255) COLLATE pg_catalog."default",
    course_reference character varying(100) COLLATE pg_catalog."default",
    training_partner_code character varying(50) COLLATE pg_catalog."default",
    claim_status character varying(50) COLLATE pg_catalog."default",
    claim_amount numeric(10, 2),
    submission_date timestamp with time zone,
    approval_date timestamp with time zone,
    payment_date timestamp with time zone,
    created_date timestamp with time zone NOT NULL DEFAULT now(),
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    raw_data jsonb,
    CONSTRAINT ssg_claims_pkey PRIMARY KEY (id),
    CONSTRAINT ssg_claims_claim_id_key UNIQUE (claim_id)
);

CREATE TABLE IF NOT EXISTS public.ssg_enrolments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    enrolment_id character varying(100) COLLATE pg_catalog."default",
    trainee_name character varying(255) COLLATE pg_catalog."default",
    trainee_nric character varying(20) COLLATE pg_catalog."default",
    course_title character varying(255) COLLATE pg_catalog."default",
    course_reference character varying(100) COLLATE pg_catalog."default",
    course_run_id character varying(100) COLLATE pg_catalog."default",
    training_partner_code character varying(50) COLLATE pg_catalog."default",
    enrolment_status character varying(50) COLLATE pg_catalog."default",
    sponsorship_type character varying(50) COLLATE pg_catalog."default",
    enrolment_date timestamp with time zone,
    completion_date timestamp with time zone,
    created_date timestamp with time zone NOT NULL DEFAULT now(),
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    raw_data jsonb,
    CONSTRAINT ssg_enrolments_pkey PRIMARY KEY (id),
    CONSTRAINT ssg_enrolments_enrolment_id_key UNIQUE (enrolment_id)
);

CREATE TABLE IF NOT EXISTS public.ssg_grants
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    enrollment_id character varying(100) COLLATE pg_catalog."default",
    reference_number character varying(100) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    funding_scheme_code character varying(50) COLLATE pg_catalog."default",
    funding_scheme_description character varying(255) COLLATE pg_catalog."default",
    component_code character varying(50) COLLATE pg_catalog."default",
    component_description character varying(255) COLLATE pg_catalog."default",
    estimated_grant_amount numeric(10, 2),
    approved_grant_amount numeric(10, 2),
    created_date timestamp with time zone NOT NULL DEFAULT now(),
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    api_response jsonb,
    CONSTRAINT ssg_grants_pkey PRIMARY KEY (id),
    CONSTRAINT ssg_grants_reference_number_key UNIQUE (reference_number)
);

CREATE TABLE IF NOT EXISTS public.submission
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    enrollment_id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    file_name text COLLATE pg_catalog."default" NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    file_url text COLLATE pg_catalog."default",
    grading text COLLATE pg_catalog."default",
    CONSTRAINT submission_pkey PRIMARY KEY (id),
    CONSTRAINT submission_enrollment_assessment_unique UNIQUE (enrollment_id, assessment_id),
    CONSTRAINT uq_submission UNIQUE (enrollment_id, assessment_id)
);

CREATE TABLE IF NOT EXISTS public.subtopic
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    learning_unit_id uuid NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    "position" integer NOT NULL DEFAULT 1,
    CONSTRAINT subtopic_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subtopic_completion
(
    enrollment_id uuid NOT NULL,
    subtopic_id uuid NOT NULL,
    completed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT subtopic_completion_pkey PRIMARY KEY (enrollment_id, subtopic_id)
);

CREATE TABLE IF NOT EXISTS public.trainer_profile
(
    user_id uuid NOT NULL,
    tel text COLLATE pg_catalog."default" NOT NULL,
    gender gender NOT NULL,
    trainer_type trainer_type NOT NULL,
    status trainer_status NOT NULL,
    linkedin_url text COLLATE pg_catalog."default",
    cv_url text COLLATE pg_catalog."default",
    qualifications jsonb DEFAULT '{}'::jsonb,
    education text COLLATE pg_catalog."default",
    areas_of_expertise jsonb DEFAULT '{}'::jsonb,
    cv_original_filename text COLLATE pg_catalog."default",
    CONSTRAINT trainer_profile_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.training_provider
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_name text COLLATE pg_catalog."default",
    company_shortname text COLLATE pg_catalog."default",
    uen text COLLATE pg_catalog."default",
    company_address text COLLATE pg_catalog."default",
    contact_person_name text COLLATE pg_catalog."default",
    contact_tel text COLLATE pg_catalog."default",
    pro_forma_template_url text COLLATE pg_catalog."default",
    invoice_template_url text COLLATE pg_catalog."default",
    receipt_template_url text COLLATE pg_catalog."default",
    certificate_template_url text COLLATE pg_catalog."default",
    ssg_self_sign_cert_file text COLLATE pg_catalog."default",
    ssg_private_key_file text COLLATE pg_catalog."default",
    ssg_encryption_key text COLLATE pg_catalog."default",
    color_scheme text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    sync_google_calendar boolean NOT NULL DEFAULT false,
    sync_ms_calendar boolean NOT NULL DEFAULT false,
    integrate_google_drive boolean NOT NULL DEFAULT false,
    integrate_ms_onedrive boolean NOT NULL DEFAULT false,
    auto_send_proforma_invoice boolean NOT NULL DEFAULT false,
    auto_send_confirm_email boolean NOT NULL DEFAULT false,
    auto_send_invoice boolean NOT NULL DEFAULT false,
    auto_send_receipt boolean NOT NULL DEFAULT false,
    auto_send_certificate boolean NOT NULL DEFAULT false,
    auto_send_thankyou_email boolean NOT NULL DEFAULT false,
    auto_mask_sensitive_data boolean NOT NULL DEFAULT false,
    auto_delete_after_six_months boolean NOT NULL DEFAULT false,
    enable_otp_login boolean NOT NULL DEFAULT false,
    enable_default_otp boolean NOT NULL DEFAULT false,
    default_otp text COLLATE pg_catalog."default",
    enable_leaderboard boolean NOT NULL DEFAULT false,
    enable_point_sys boolean NOT NULL DEFAULT false,
    normal_fund_rate numeric,
    enhanced_fund_rate numeric,
    gst_rate numeric,
    gst_register boolean NOT NULL DEFAULT false,
    CONSTRAINT training_provider_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.training_provider_api
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    training_provider_id uuid NOT NULL,
    key_name text COLLATE pg_catalog."default" NOT NULL,
    key_value text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT training_provider_api_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role_map
(
    user_id uuid NOT NULL,
    role user_role NOT NULL,
    CONSTRAINT user_role_map_pkey PRIMARY KEY (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.user_saved_job
(
    user_id uuid NOT NULL,
    job_posting_id uuid NOT NULL,
    saved_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_saved_job_pkey PRIMARY KEY (user_id, job_posting_id)
);

CREATE TABLE IF NOT EXISTS public.user_subtopic_bookmark
(
    user_id uuid NOT NULL,
    subtopic_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    course_run_id uuid NOT NULL,
    CONSTRAINT user_subtopic_bookmark_pkey PRIMARY KEY (user_id, subtopic_id, course_run_id)
);

CREATE TABLE IF NOT EXISTS public.work_experience
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    trainer_id uuid,
    company text COLLATE pg_catalog."default" NOT NULL,
    job_title text COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    developer_id uuid,
    CONSTRAINT trainer_work_experience_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.admin_profile
    ADD CONSTRAINT admin_profile_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS admin_profile_pkey
    ON public.admin_profile(user_id);


ALTER TABLE IF EXISTS public.assessment
    ADD CONSTRAINT assessment_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.assessment_grade
    ADD CONSTRAINT assessment_grade_assessment_id_fkey FOREIGN KEY (assessment_id)
    REFERENCES public.assessment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.assessment_grade
    ADD CONSTRAINT assessment_grade_enrollment_id_fkey FOREIGN KEY (enrollment_id)
    REFERENCES public.enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.calendar_event
    ADD CONSTRAINT calendar_event_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.certification
    ADD CONSTRAINT certification_developer_id_fkey FOREIGN KEY (developer_id)
    REFERENCES public.developer_profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.certification
    ADD CONSTRAINT fk_trainer_certification_trainer FOREIGN KEY (trainer_id)
    REFERENCES public.trainer_profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_conversation
    ADD CONSTRAINT chat_conversation_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_message
    ADD CONSTRAINT chat_message_conversation_id_fkey FOREIGN KEY (conversation_id)
    REFERENCES public.chat_conversation (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_run
    ADD CONSTRAINT course_run_assigned_trainer_id_fkey FOREIGN KEY (assigned_trainer_id)
    REFERENCES public.trainer_profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.course_run
    ADD CONSTRAINT course_run_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_course_run_course
    ON public.course_run(course_id);


ALTER TABLE IF EXISTS public.course_run_assessment
    ADD CONSTRAINT course_run_assessment_assessment_id_fkey FOREIGN KEY (assessment_id)
    REFERENCES public.assessment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_run_assessment
    ADD CONSTRAINT course_run_assessment_course_run_id_fkey FOREIGN KEY (course_run_id)
    REFERENCES public.course_run (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.developer_profile
    ADD CONSTRAINT developer_profile_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS developer_profile_pkey
    ON public.developer_profile(user_id);


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollment_course
    ON public.enrollment(course_id);


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_course_run_id_fkey FOREIGN KEY (course_run_id)
    REFERENCES public.course_run (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollment_user
    ON public.enrollment(user_id);


ALTER TABLE IF EXISTS public.learner_profile
    ADD CONSTRAINT learner_profile_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS learner_profile_pkey
    ON public.learner_profile(user_id);


ALTER TABLE IF EXISTS public.learning_unit
    ADD CONSTRAINT learning_unit_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider_admin_user
    ADD CONSTRAINT provider_admin_user_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.training_provider (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider_admin_user
    ADD CONSTRAINT provider_admin_user_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.submission
    ADD CONSTRAINT submission_assessment_id_fkey FOREIGN KEY (assessment_id)
    REFERENCES public.assessment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.submission
    ADD CONSTRAINT submission_enrollment_id_fkey FOREIGN KEY (enrollment_id)
    REFERENCES public.enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_submission_enroll
    ON public.submission(enrollment_id);


ALTER TABLE IF EXISTS public.subtopic
    ADD CONSTRAINT subtopic_learning_unit_id_fkey FOREIGN KEY (learning_unit_id)
    REFERENCES public.learning_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subtopic_completion
    ADD CONSTRAINT subtopic_completion_enrollment_id_fkey FOREIGN KEY (enrollment_id)
    REFERENCES public.enrollment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subtopic_completion
    ADD CONSTRAINT subtopic_completion_subtopic_id_fkey FOREIGN KEY (subtopic_id)
    REFERENCES public.subtopic (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.trainer_profile
    ADD CONSTRAINT trainer_profile_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS trainer_profile_pkey
    ON public.trainer_profile(user_id);


ALTER TABLE IF EXISTS public.training_provider_api
    ADD CONSTRAINT fk_training_provider_api_provider FOREIGN KEY (training_provider_id)
    REFERENCES public.training_provider (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_role_map
    ADD CONSTRAINT user_role_map_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_saved_job
    ADD CONSTRAINT user_saved_job_job_posting_id_fkey FOREIGN KEY (job_posting_id)
    REFERENCES public.job_posting (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_saved_job
    ADD CONSTRAINT user_saved_job_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_subtopic_bookmark
    ADD CONSTRAINT fk_user_subtopic_bookmark_course_run FOREIGN KEY (course_run_id)
    REFERENCES public.course_run (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_subtopic_bookmark
    ADD CONSTRAINT user_subtopic_bookmark_subtopic_id_fkey FOREIGN KEY (subtopic_id)
    REFERENCES public.subtopic (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_subtopic_bookmark
    ADD CONSTRAINT user_subtopic_bookmark_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.work_experience
    ADD CONSTRAINT fk_trainer_work_experience_trainer FOREIGN KEY (trainer_id)
    REFERENCES public.trainer_profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.work_experience
    ADD CONSTRAINT work_experience_developer_id_fkey FOREIGN KEY (developer_id)
    REFERENCES public.developer_profile (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;