import type { calendar_v3 } from 'googleapis';
import pool from '../db';
import { getCalendarClient } from './calendarClient';
import { findEventOnDate, stripPrefixes, eventBelongsToRun } from './eventMatch';
import { getTrainingPartnerIdentifiers } from '../trainingPartnerIdentifiers';

/**
 * Single, idempotent "make the class's calendar events exist" helper + its
 * counterparts (remove, attendee-sync). Replaces the fuzzy-match-only model with
 * a durable per-session-date mapping (course_run_calendar_event) guarded by a
 * Postgres advisory lock, so creation is exact and race-safe.
 *
 * NOTE: creation matches the CA/DA title/description format ("WSQ - <title>",
 * with "Course Run ID: <ssgId>" in the description) so the existing CA/DA
 * matchers adopt these events and vice-versa — they coexist without duplicating.
 */

const SGT = 'Asia/Singapore';

const sessionIso = (v: string | null): string | null => {
  if (!v) return null;
  const s = String(v).replace(/-/g, '');
  return s.length >= 8 ? `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}` : null;
};

const baseOf = (eventId: string | null | undefined): string | null =>
  eventId && eventId.includes('_') ? eventId.split('_')[0] : null;

interface RunMeta {
  id: string; course_run_id: string; course_code: string | null;
  title: string; start_date: string | null; end_date: string | null;
}

async function loadRun(courseRunId: string): Promise<RunMeta | null> {
  const r = await pool.query<RunMeta>(
    `SELECT cr.id, cr.course_run_id, c.course_code, c.title,
            cr.start_date::text AS start_date, cr.end_date::text AS end_date
       FROM course_run cr JOIN course c ON c.id = cr.course_id
      WHERE cr.id::text = $1 OR cr.course_run_id = $1 LIMIT 1`,
    [courseRunId]
  );
  return r.rows[0] ?? null;
}

async function sessionDates(runUuid: string, fallbackStart: string | null): Promise<string[]> {
  const sess = (await pool.query(
    `SELECT DISTINCT start_date FROM course_session WHERE course_run_id = $1 AND (deleted IS NOT TRUE)`,
    [runUuid]
  )).rows;
  let dates = sess.map(r => sessionIso(r.start_date)).filter(Boolean) as string[];
  if (dates.length === 0 && fallbackStart) dates = [String(fallbackStart).slice(0, 10)];
  return Array.from(new Set(dates)).sort();
}

/** Run `fn` while holding a per-course-run advisory lock (cross-request safe). */
async function withRunLock<T>(runUuid: string, fn: () => Promise<T>): Promise<T> {
  const client = await pool.connect();
  try {
    await client.query(`SELECT pg_advisory_lock(hashtext($1))`, [`class-cal:${runUuid}`]);
    return await fn();
  } finally {
    await client.query(`SELECT pg_advisory_unlock(hashtext($1))`, [`class-cal:${runUuid}`]).catch(() => {});
    client.release();
  }
}

export interface EnsureResult { status: 'ok' | 'skipped'; created: number; adopted: number; kept: number; errors: number; reason?: string; }

/**
 * Ensure a calendar event exists for every session date of the class. Does NOT
 * touch attendees (see syncClassAttendees). Idempotent + advisory-locked.
 */
export async function ensureClassCalendarEvent(courseRunId: string): Promise<EnsureResult> {
  const out: EnsureResult = { status: 'ok', created: 0, adopted: 0, kept: 0, errors: 0 };
  const client = await getCalendarClient();
  if (!client) return { ...out, status: 'skipped', reason: 'calendar sync disabled' };
  const run = await loadRun(courseRunId);
  if (!run) return { ...out, status: 'skipped', reason: 'course run not found' };
  const dates = await sessionDates(run.id, run.start_date);
  if (dates.length === 0) return { ...out, status: 'skipped', reason: 'no session dates' };

  const { calendar, calendarId } = client;
  const cleanTitle = stripPrefixes(run.title || '');
  const title = `WSQ - ${cleanTitle}`;

  let tpAddress = 'Office';
  try { tpAddress = (await getTrainingPartnerIdentifiers()).companyAddress || 'Office'; } catch { /* default */ }
  const isVirtual = /virtual|online|e-learning/i.test(run.title || '');
  const location = isVirtual ? 'Virtual / Online' : tpAddress;
  const description = `Course Title: ${run.title}\nCourse Code: ${run.course_code || 'N/A'}\nCourse Run ID: ${run.course_run_id || 'N/A'}\n\n*Auto-generated by LMS*`;

  return withRunLock(run.id, async () => {
    // One events.list across the whole window, reused for all dates.
    const timeMin = new Date(dates[0] + 'T00:00:00Z'); timeMin.setUTCDate(timeMin.getUTCDate() - 1);
    const timeMax = new Date(dates[dates.length - 1] + 'T00:00:00Z'); timeMax.setUTCDate(timeMax.getUTCDate() + 2);
    let events: calendar_v3.Schema$Event[] = [];
    try {
      events = (await calendar.events.list({ calendarId, timeMin: timeMin.toISOString(), timeMax: timeMax.toISOString(), singleEvents: true, maxResults: 250 })).data.items || [];
    } catch (e) { /* will fall through to create */ }

    for (const dateIso of dates) {
      try {
        // 1) exact path — stored mapping that still exists in Calendar
        const mapped = (await pool.query(
          `SELECT google_event_id FROM course_run_calendar_event WHERE course_run_id = $1 AND event_date = $2::date`,
          [run.id, dateIso]
        )).rows[0];
        if (mapped?.google_event_id) {
          // NOTE: a manually-DELETED event is not a 404 — Google's events.get returns it with
          // status:'cancelled' (and events.list excludes cancelled by default). So "get succeeded"
          // is NOT proof it's live; we must check status !== 'cancelled', else a deleted event is
          // wrongly "kept" and never recreated.
          const live = events.find(e => e.id === mapped.google_event_id)
            || await calendar.events.get({ calendarId, eventId: mapped.google_event_id }).then(r => r.data).catch(() => null);
          if (live && live.status !== 'cancelled') { out.kept++; continue; }
          // stored event vanished (404) or was deleted/cancelled — drop the stale row, fall through to adopt/create
          await pool.query(`DELETE FROM course_run_calendar_event WHERE course_run_id = $1 AND event_date = $2::date`, [run.id, dateIso]);
        }

        // 2) adopt path — an existing event matches this class+date
        const match = findEventOnDate(events, { courseRunId: run.course_run_id, courseTitle: run.title, dateIso });
        if (match?.id) {
          const ins = await pool.query(
            `INSERT INTO course_run_calendar_event (course_run_id, event_date, google_event_id, base_event_id)
             VALUES ($1, $2::date, $3, $4) ON CONFLICT (google_event_id) DO NOTHING`,
            [run.id, dateIso, match.id, baseOf(match.id)]
          );
          if (ins.rowCount && ins.rowCount > 0) out.adopted++; else out.kept++;
          continue;
        }

        // 3) create path
        const created = await calendar.events.insert({
          calendarId,
          requestBody: {
            summary: title, description, location,
            start: { dateTime: `${dateIso}T09:30:00`, timeZone: SGT },
            end: { dateTime: `${dateIso}T18:30:00`, timeZone: SGT },
            guestsCanInviteOthers: false, guestsCanSeeOtherGuests: false,
          },
          sendUpdates: 'none',
        });
        if (created.data.id) {
          await pool.query(
            `INSERT INTO course_run_calendar_event (course_run_id, event_date, google_event_id, base_event_id)
             VALUES ($1, $2::date, $3, $4) ON CONFLICT (course_run_id, event_date) DO UPDATE SET google_event_id = EXCLUDED.google_event_id, updated_at = now()`,
            [run.id, dateIso, created.data.id, baseOf(created.data.id)]
          );
          out.created++;
        } else { out.errors++; }
      } catch (e) { out.errors++; }
    }
    return out;
  });
}

export interface RemoveResult { status: 'ok' | 'skipped'; removed: number; errors: number; reason?: string; }

/**
 * Remove all calendar events for a class (cancellation / last-learner-removed).
 *
 * Live-match based (Phase 3): removes the UNION of
 *   (a) every event in the durable mapping (by id — caught regardless of date), and
 *   (b) every event in the run's date window whose description/location carries the
 *       run id (`eventBelongsToRun`) — catches events whose map row drifted or was
 *       lost, so a cancel can't silently orphan them.
 * cancel-patches events that had attendees, hard-deletes empty ones, clears rows.
 */
export async function removeClassCalendarEvents(courseRunId: string, _opts: { reason?: string } = {}): Promise<RemoveResult> {
  const out: RemoveResult = { status: 'ok', removed: 0, errors: 0 };
  const client = await getCalendarClient();
  if (!client) return { ...out, status: 'skipped', reason: 'calendar sync disabled' };
  const run = await loadRun(courseRunId);
  if (!run) return { ...out, status: 'skipped', reason: 'course run not found' };
  const { calendar, calendarId } = client;

  return withRunLock(run.id, async () => {
    // (a) Mapped event ids — removed by id, regardless of where they now live.
    const mapped = (await pool.query<{ google_event_id: string }>(
      `SELECT google_event_id FROM course_run_calendar_event WHERE course_run_id = $1`,
      [run.id]
    )).rows;
    const ids = new Set<string>(mapped.map(r => r.google_event_id));

    // (b) Live-match: any event in the run's window carrying the run id but NOT in
    //     the map (a drifted / orphaned event). Best-effort; falls back to (a) only.
    try {
      const dates = await sessionDates(run.id, run.start_date);
      const loBase = dates[0] || (run.start_date ? String(run.start_date).slice(0, 10) : null);
      const hiBase = (run.end_date ? String(run.end_date).slice(0, 10) : null) || dates[dates.length - 1] || loBase;
      if (loBase && hiBase) {
        const lo = new Date(loBase + 'T00:00:00Z'); lo.setUTCDate(lo.getUTCDate() - 1);
        const hi = new Date(hiBase + 'T00:00:00Z'); hi.setUTCDate(hi.getUTCDate() + 2);
        const events = (await calendar.events.list({ calendarId, timeMin: lo.toISOString(), timeMax: hi.toISOString(), singleEvents: true, maxResults: 250 })).data.items || [];
        for (const e of events) {
          if (e.id && !ids.has(e.id) && eventBelongsToRun(e, run.course_run_id)) ids.add(e.id);
        }
      }
    } catch { /* fall back to mapped-only removal */ }

    for (const eventId of ids) {
      try {
        const evt = await calendar.events.get({ calendarId, eventId }).then(r => r.data).catch(() => null);
        if (evt && evt.status !== 'cancelled') {
          if ((evt.attendees || []).length > 0) {
            await calendar.events.patch({ calendarId, eventId, requestBody: { status: 'cancelled' }, sendUpdates: 'none' });
          } else {
            await calendar.events.delete({ calendarId, eventId, sendUpdates: 'none' });
          }
          out.removed++;
        }
        await pool.query(`DELETE FROM course_run_calendar_event WHERE course_run_id = $1 AND google_event_id = $2`, [run.id, eventId]);
      } catch (e) { out.errors++; }
    }
    return out;
  });
}

export interface AttendeeSyncResult { status: 'ok' | 'skipped'; added: number; removed: number; errors: number; reason?: string; }

/**
 * Reconcile each event's attendees to the class's desired set =
 * confirmed learners + accepted trainers. Adds anyone missing; removes only
 * attendees the LMS recognizes as departed learners/trainers — never strips
 * unknown (manually-added) attendees. Patches every recurring instance.
 */
export async function syncClassAttendees(courseRunId: string): Promise<AttendeeSyncResult> {
  const out: AttendeeSyncResult = { status: 'ok', added: 0, removed: 0, errors: 0 };
  const client = await getCalendarClient();
  if (!client) return { ...out, status: 'skipped', reason: 'calendar sync disabled' };
  const run = await loadRun(courseRunId);
  if (!run) return { ...out, status: 'skipped', reason: 'course run not found' };
  const { calendar, calendarId } = client;

  // Desired = confirmed learners + local trainers + the TPG-assigned trainer (lowercased emails).
  // The TPG trainer is included so the actual SSG/TPG trainer lands on the calendar even when
  // they aren't (yet) a local course_run_trainer.
  const desiredRows = await pool.query<{ email: string }>(
    `SELECT lower(btrim(au.email)) AS email
       FROM enrollment e JOIN app_user au ON au.id = e.user_id
      WHERE e.course_run_id = $1 AND e.enrolment_status = 'Confirmed' AND nullif(btrim(au.email),'') IS NOT NULL
      UNION
     SELECT lower(btrim(t.trainer_email)) AS email
       FROM course_run_trainer t WHERE t.course_run_id = $1 AND nullif(btrim(t.trainer_email),'') IS NOT NULL
      UNION
     SELECT lower(btrim(cr.tpg_assigned_trainer_email)) AS email
       FROM course_run cr WHERE cr.id = $1 AND nullif(btrim(cr.tpg_assigned_trainer_email),'') IS NOT NULL`,
    [run.id]
  );
  const desired = new Set(desiredRows.rows.map(r => r.email));

  // Known LMS-managed emails (any enrollment status + any current/invited trainer)
  // — only these may be removed if not desired; everyone else on the event is left
  // alone. trainer_invitation is included so a trainer who was REMOVED (their
  // course_run_trainer row is hard-deleted, e.g. on Unconfirm or remove-trainer)
  // is still recognized as departed and dropped from the event.
  const knownRows = await pool.query<{ email: string }>(
    `SELECT lower(btrim(au.email)) AS email FROM enrollment e JOIN app_user au ON au.id=e.user_id WHERE e.course_run_id=$1 AND nullif(btrim(au.email),'') IS NOT NULL
     UNION SELECT lower(btrim(t.trainer_email)) FROM course_run_trainer t WHERE t.course_run_id=$1 AND nullif(btrim(t.trainer_email),'') IS NOT NULL
     UNION SELECT lower(btrim(ti.trainer_email)) FROM trainer_invitation ti WHERE ti.course_run_id=$1 AND nullif(btrim(ti.trainer_email),'') IS NOT NULL
     UNION SELECT lower(btrim(cr.tpg_assigned_trainer_email)) FROM course_run cr WHERE cr.id=$1 AND nullif(btrim(cr.tpg_assigned_trainer_email),'') IS NOT NULL`,
    [run.id]
  );
  const known = new Set(knownRows.rows.map(r => r.email));

  return withRunLock(run.id, async () => {
    const eventIds = (await pool.query<{ google_event_id: string }>(
      `SELECT google_event_id FROM course_run_calendar_event WHERE course_run_id = $1`, [run.id]
    )).rows.map(r => r.google_event_id);

    for (const eventId of eventIds) {
      try {
        const evt = await calendar.events.get({ calendarId, eventId }).then(r => r.data).catch(() => null);
        if (!evt) continue;
        const current = evt.attendees || [];
        const currentEmails = new Set(current.map(a => (a.email || '').toLowerCase()));

        const toAdd = [...desired].filter(e => !currentEmails.has(e));
        // Keep attendees that are still desired OR are unknown (externally-added).
        // This drops only known-LMS emails that are no longer desired (departed).
        const kept = current.filter(a => {
          const em = (a.email || '').toLowerCase();
          return desired.has(em) || !known.has(em);
        });
        const removedCount = current.length - kept.length;
        if (toAdd.length === 0 && removedCount === 0) continue; // no change

        const next: calendar_v3.Schema$EventAttendee[] = [...kept];
        for (const email of toAdd) next.push({ email, responseStatus: 'needsAction' });

        await calendar.events.patch({ calendarId, eventId, requestBody: { attendees: next }, sendUpdates: 'none' });
        out.added += toAdd.length;
        out.removed += removedCount;
      } catch (e) { out.errors++; }
    }
    return out;
  });
}
