import { google } from 'googleapis';
import { Pool } from 'pg';
import * as dotenv from 'dotenv';
import { getGoogleCredentials } from '../lib/google-auth/googleAuth';

dotenv.config({ path: '.env.local' });

async function run() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });
  
  try {
    const credentials = await getGoogleCredentials(pool);
    const oauth2Client = new google.auth.OAuth2(credentials.clientId, credentials.clientSecret);
    oauth2Client.setCredentials({ refresh_token: credentials.refreshToken });
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client });

    const tpRes = await pool.query('SELECT google_calendar_url FROM training_provider LIMIT 1');
    let calendarId = 'primary';
    const calUrl = tpRes.rows[0]?.google_calendar_url || '';
    if (calUrl.includes('@')) calendarId = calUrl;
    else if (calUrl.match(/[?&]cid=([^&]+)/)) {
        const match = calUrl.match(/[?&]cid=([^&]+)/);
        if (match) {
            try { calendarId = Buffer.from(match[1], 'base64').toString('utf-8'); } catch { calendarId = match[1]; }
        }
    }

    console.log(`Processing events in calendar: ${calendarId}`);
    
    // We want events created "yesterday" (2026-04-22)
    // But since list doesn't support 'created' filter easily, we search for all recent and check the 'created' field
    const timeMin = '2026-04-20T00:00:00Z'; // Wide window
    
    const res = await calendar.events.list({
      calendarId,
      timeMin,
      q: 'Auto-generated by LMS',
      singleEvents: true,
      maxResults: 2500
    });

    const events = res.data.items || [];
    console.log(`Found ${events.length} system events to inspect.`);

    let updateCount = 0;
    const physicalAddress = "12 Woodlands Square #07-85/86/87 Woods Square Tower 1, Singapore 737715 Map https://g.page/tertiarycourses-sg?share";

    for (const evt of events) {
      // Check if created yesterday (2026-04-22)
      const createdDate = evt.created?.slice(0, 10);
      const isCreatedYesterday = createdDate === '2026-04-22';
      
      // Also check if it's one of the ones the user was just talking about (today is 2026-04-23)
      // Actually, "created yesterday" is the filter requested.
      
      if (isCreatedYesterday && evt.description?.includes('*Auto-generated by LMS*')) {
        console.log(`Inspecting: "${evt.summary}" (Created: ${createdDate})`);
        
        // Parse metadata from description
        const desc = evt.description || '';
        const titleMatch = desc.match(/Course Title: (.*)/);
        const runIdMatch = desc.match(/Course Run ID: (.*)/);
        
        const courseTitle = titleMatch ? titleMatch[1].trim() : '';
        const runId = runIdMatch ? runIdMatch[1].trim() : '';
        
        // Clean title
        const cleanTitle = courseTitle
            .replace(/^\s*Day\s*\d+[\s-:]*/gi, '')
            .replace(/^\s*\[?(WSQ|VIRTUAL|EXTERNAL|HYBRID|E-LEARNING)\]?[\s-]*/gi, '')
            .replace(/^[\s-:]+|[\s-:]+$/g, '')
            .trim();

        // Extract Day X from current summary if present
        const dayMatch = evt.summary?.match(/Day\s*(\d+)/i);
        const dayNumber = dayMatch ? dayMatch[1] : null;

        // Reconstruct title: [Day X] - WSQ - [Course Title] - [Run ID]
        const titleParts: string[] = [];
        if (dayNumber) titleParts.push(`Day ${dayNumber}`);
        titleParts.push("WSQ");
        if (cleanTitle) titleParts.push(cleanTitle);
        if (runId && runId !== 'N/A') titleParts.push(runId);
        const newTitle = titleParts.join(' - ');

        // Location
        const isVirtual = /virtual|online|e-learning/i.test(courseTitle);
        const expectedLocation = isVirtual ? "Virtual / Online" : physicalAddress;

        const needsTitleUpdate = evt.summary !== newTitle;
        const needsLocationUpdate = evt.location !== expectedLocation;

        if (needsTitleUpdate || needsLocationUpdate) {
          console.log(`  UPDATING:`);
          if (needsTitleUpdate) console.log(`    Title: "${evt.summary}" -> "${newTitle}"`);
          if (needsLocationUpdate) console.log(`    Location: "${evt.location || 'None'}" -> "${expectedLocation}"`);
          
          await calendar.events.patch({
            calendarId,
            eventId: evt.id!,
            requestBody: {
              summary: newTitle,
              location: expectedLocation,
              // Also ensure permissions are set while we are at it
              guestsCanInviteOthers: false,
              guestsCanSeeOtherGuests: false
            }
          });
          updateCount++;
        }
      }
    }

    console.log(`\nSuccessfully updated ${updateCount} events.`);
  } catch (err) {
    console.error('Fatal error:', err);
  } finally {
    await pool.end();
  }
}

run();
