import { google } from 'googleapis';
import { Pool } from 'pg';
import * as dotenv from 'dotenv';
import { getGoogleCredentials } from '../lib/google-auth/googleAuth';

dotenv.config({ path: '.env.local' });

async function run() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });
  
  try {
    const credentials = await getGoogleCredentials(pool);
    const oauth2Client = new google.auth.OAuth2(credentials.clientId, credentials.clientSecret);
    oauth2Client.setCredentials({ refresh_token: credentials.refreshToken });
    const calendar = google.calendar({ version: 'v3', auth: oauth2Client });

    const tpRes = await pool.query('SELECT google_calendar_url FROM training_provider LIMIT 1');
    let calendarId = 'primary';
    const calUrl = tpRes.rows[0]?.google_calendar_url || '';
    if (calUrl.includes('@')) calendarId = calUrl;
    else if (calUrl.match(/[?&]cid=([^&]+)/)) {
        const match = calUrl.match(/[?&]cid=([^&]+)/);
        if (match) {
            try { calendarId = Buffer.from(match[1], 'base64').toString('utf-8'); } catch { calendarId = match[1]; }
        }
    }

    console.log(`Searching for system-generated events in calendar: ${calendarId}`);
    
    // Search for events from the past 7 days and into the future
    const now = new Date();
    const timeMin = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString();
    
    const res = await calendar.events.list({
      calendarId,
      timeMin,
      q: 'Auto-generated by LMS',
      singleEvents: true,
      maxResults: 2500
    });

    const events = res.data.items || [];
    console.log(`Found ${events.length} potential events to update.`);

    let updateCount = 0;
    for (const evt of events) {
      if (evt.description?.includes('*Auto-generated by LMS*')) {
        // Only update if permissions are currently allowed (or just force set them)
        if (evt.guestsCanInviteOthers !== false || evt.guestsCanSeeOtherGuests !== false) {
          console.log(`Updating event: "${evt.summary}" on ${evt.start?.dateTime || evt.start?.date}`);
          await calendar.events.patch({
            calendarId,
            eventId: evt.id!,
            requestBody: {
              guestsCanInviteOthers: false,
              guestsCanSeeOtherGuests: false
            }
          });
          updateCount++;
        }
      }
    }

    console.log(`\nSuccessfully updated ${updateCount} events.`);
  } catch (err) {
    console.error('Fatal error:', err);
  } finally {
    await pool.end();
  }
}

run();
