import React from 'react';
import { Card } from '../ui/Card';
import { Icon, IconName } from '../ui/Icon';

interface Step {
  number: number;
  title: string;
  description: string;
  actor: 'trainer' | 'learner' | 'system';
  icon: IconName;
}

const STEPS: Step[] = [
  {
    number: 1,
    title: 'Trainer Publishes the Assessment',
    description: 'The trainer creates and publishes the assessment for the course. The assessment becomes available for learners to access.',
    actor: 'trainer',
    icon: IconName.Upload,
  },
  {
    number: 2,
    title: 'Learner Downloads the Assessment',
    description: 'The learner downloads the digital Word document from the assessment section in the LMS.',
    actor: 'learner',
    icon: IconName.Download,
  },
  {
    number: 3,
    title: 'Learner Completes the Assessment',
    description: 'The learner works on the assessment by filling in their answers in the downloaded document.',
    actor: 'learner',
    icon: IconName.Edit,
  },
  {
    number: 4,
    title: 'Learner Submits the Assessment',
    description: 'The learner uploads and submits the completed digital copy of the assessment answers back into the LMS.',
    actor: 'learner',
    icon: IconName.Send,
  },
  {
    number: 5,
    title: 'Assessment Filed in Trainee Sub-Folder',
    description: 'The submitted assessment answers are automatically placed in the respective trainee sub-folder on Google Drive for organised record keeping.',
    actor: 'system',
    icon: IconName.FileText,
  },
  {
    number: 6,
    title: 'Trainer Reviews the Assessment',
    description: 'The trainer checks the learner\'s assessment answers from the Assessment folder link on Google Drive.',
    actor: 'trainer',
    icon: IconName.Eye,
  },
  {
    number: 7,
    title: 'Trainer Amends & Re-uploads',
    description: 'If necessary, the trainer amends the answers and re-uploads the corrected assessment to Google Drive.',
    actor: 'trainer',
    icon: IconName.Upload,
  },
  {
    number: 8,
    title: 'Trainer Marks as Competent',
    description: 'The trainer marks the learner as competent if they meet the assessment criteria.',
    actor: 'trainer',
    icon: IconName.CheckCircle,
  },
  {
    number: 9,
    title: 'Certificate Auto-Generated',
    description: 'Once the trainer marks the learner as competent, the certificate is automatically generated by the system.',
    actor: 'system',
    icon: IconName.Award,
  },
];

const actorColors = {
  trainer: {
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    border: 'border-blue-200 dark:border-blue-800',
    badge: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
    iconBg: 'bg-blue-100 dark:bg-blue-900/40',
    iconText: 'text-blue-600 dark:text-blue-400',
    connector: 'border-blue-300 dark:border-blue-700',
    number: 'bg-blue-600 dark:bg-blue-500',
  },
  learner: {
    bg: 'bg-green-50 dark:bg-green-900/20',
    border: 'border-green-200 dark:border-green-800',
    badge: 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300',
    iconBg: 'bg-green-100 dark:bg-green-900/40',
    iconText: 'text-green-600 dark:text-green-400',
    connector: 'border-green-300 dark:border-green-700',
    number: 'bg-green-600 dark:bg-green-500',
  },
  system: {
    bg: 'bg-purple-50 dark:bg-purple-900/20',
    border: 'border-purple-200 dark:border-purple-800',
    badge: 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300',
    iconBg: 'bg-purple-100 dark:bg-purple-900/40',
    iconText: 'text-purple-600 dark:text-purple-400',
    connector: 'border-purple-300 dark:border-purple-700',
    number: 'bg-purple-600 dark:bg-purple-500',
  },
};

const actorLabels = { trainer: 'Trainer', learner: 'Learner', system: 'System' };

const AssessmentGuidePage: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="border-b border-gray-200 dark:border-gray-700 pb-5">
        <h3 className="text-2xl font-bold leading-6 text-gray-900 dark:text-white flex items-center gap-2">
          <Icon name={IconName.BookOpen} className="w-7 h-7" />
          Assessment Guide
        </h3>
        <p className="mt-2 max-w-4xl text-sm text-gray-500 dark:text-gray-400">
          Step-by-step visual guide on how assessments are conducted in the LMS.
        </p>
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-4">
        {(['trainer', 'learner', 'system'] as const).map((actor) => (
          <div key={actor} className="flex items-center gap-2">
            <span className={`inline-block w-3 h-3 rounded-full ${actorColors[actor].number}`} />
            <span className="text-sm text-gray-600 dark:text-gray-400">{actorLabels[actor]}</span>
          </div>
        ))}
      </div>

      {/* Flow Steps */}
      <div className="relative">
        {STEPS.map((step, index) => {
          const colors = actorColors[step.actor];
          const isLast = index === STEPS.length - 1;

          return (
            <div key={step.number} className="relative flex gap-4">
              {/* Vertical connector line + step number */}
              <div className="flex flex-col items-center">
                <div className={`w-10 h-10 rounded-full ${colors.number} text-white flex items-center justify-center text-sm font-bold flex-shrink-0 z-10`}>
                  {step.number}
                </div>
                {!isLast && (
                  <div className="w-0.5 flex-1 bg-gray-200 dark:bg-gray-700 my-1" />
                )}
              </div>

              {/* Step card */}
              <div className={`flex-1 mb-4 rounded-lg border ${colors.border} ${colors.bg} p-4`}>
                <div className="flex items-start gap-3">
                  <div className={`p-2 rounded-lg ${colors.iconBg} flex-shrink-0`}>
                    <Icon name={step.icon} className={`w-5 h-5 ${colors.iconText}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="text-sm font-semibold text-gray-900 dark:text-white">{step.title}</h4>
                      <span className={`text-[10px] font-semibold uppercase px-2 py-0.5 rounded-full ${colors.badge}`}>
                        {actorLabels[step.actor]}
                      </span>
                    </div>
                    <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">{step.description}</p>
                  </div>
                </div>

                {/* Arrow indicator for flow direction */}
                {!isLast && (
                  <div className="flex justify-center mt-2">
                    <Icon name={IconName.ChevronDown} className="w-4 h-4 text-gray-400 dark:text-gray-500" />
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default AssessmentGuidePage;
